

import java.util.Scanner;

public class TeacherList {
	public static Teacher[] MakeList(){
		Teacher[] teachers=new Teacher[71];	
		Scanner iScanner = null;
		String thingString="Dae Yi\n"
				+"BCMS\n"
				+"4A, 6\n"
				+"Cricket, Breakdancing Club, Ultimate Frisbee Club, Class of 2014\n"
				+"null\n"
				+"dae_yi@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Heather Casseta\n"
				+"Science\n"
				+"4A, 4B\n"
				+"null\n"
				+"null\n"
				+"heather_casseta@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Vann Prime\n"
				+"Social Studies\n"
				+"3, 4B\n"
				+"Economics Challenge, Mock Trial, Model United Debate, Debate\n"
				+"null\n"
				+"vann_prime@hcpss.org\n"
				+"www.veepu.com\n"
				+"'\n"
				+"Michael Gorleski\n"
				+"CTE\n"
				+"5, 6\n"
				+"FBLA, STEM\n"
				+"null\n"
				+"michael_gorleski@hcpss.org\n"
				+"mrgorleski.com\n"
				+"'\n"
				+"Alice Pham\n"
				+"World Languages\n"
				+"4B, 6\n"
				+"null\n"
				+"null\n"
				+"apahm@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Bernadette Bechta\n"
				+"BCMC\n"
				+"1, 6\n"
				+"Tetris Club\n"
				+"null\n"
				+"bbechta@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Michael McCarthy\n"
				+"Bus/Health - PE\n"
				+"4B, 5\n"
				+"null\n"
				+"JV Football\n"
				+"Varsity Boys Lacrosse\n"
				+"Michael_McCarthy@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Eric Duke\n"
				+"Social Studies\n"
				+"4A, 4B\n"
				+"null\n"
				+"null\n"
				+"eric_duke@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Dianna Ricker\n"
				+"English\n"
				+"1, 5\n"
				+"null\n"
				+"null\n"
				+"diana_ricker@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"James Kroll\n"
				+"Music\n"
				+"4A, 5\n"
				+"World Instruments and Music\n"
				+"null\n"
				+"james_kroll@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Mary Kate Hannah\n"
				+"Art\n"
				+"2, 6\n"
				+"National Art Honor Society\n"
				+"null\n"
				+"Mary_Hannah@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Robert Gibbons\n"
				+"BCMS\n"
				+"2, 3\n"
				+"null\n"
				+"Varsity Girls Soccer, JV Girls Soccer, JV Girls Softball\n"
				+"Robert_Gibbons@hcpss.org\n"
				+"Hebron-Soccer.com\n"
				+"'\n"
				+"Steve Beninghove\n"
				+"Mathematics\n"
				+"3, 5\n"
				+"null\n"
				+"JV Boys Lacrosse\n"
				+"stepen_beninghove@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Matt Gittermann\n"
				+"Science\n"
				+"2, 6\n"
				+"null\n"
				+"null\n"
				+"matt_gittermann@hcpss.org\n"
				+"mr.gittermann.weebly.com\n"
				+"'\n"
				+"Christina Crise\n"
				+"World Languages\n"
				+"3, 4B\n"
				+"French Club\n"
				+"null\n"
				+"Christina_Crise@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Michelle Mann\n"
				+"Special Education/Mathematics\n"
				+"4A, 4B\n"
				+"null\n"
				+"null\n"
				+"michelle_mann@hcpss.org\n"
				+"http://algebra1seminar.weebly.com\n"
				+"'\n"
				+"Michelle Vealey\n"
				+"Mathematics\n"
				+"4A, 4B\n"
				+"Ice Hockey\n"
				+"null\n"
				+"Michelle_Vealey@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Alyson Donoghue\n"
				+"Science\n"
				+"5, 6\n"
				+"null\n"
				+"null\n"
				+"alyson_donoghue@hcpss.org\n"
				+"http://adonoghue.weebly.com\n"
				+"'\n"
				+"Mary Ann Sankey\n"
				+"Science\n"
				+"4B, 5\n"
				+"National Honor Society\n"
				+"null\n"
				+"mary_sankey@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Rebecca Maerten\n"
				+"World Languages\n"
				+"4B, 6\n"
				+"Aquatics/Swim Club\n"
				+"German Club\n"
				+"null\n"
				+"rebecca_maetren@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Jennifer Sherman\n"
				+"Art\n"
				+"3, 6\n"
				+"National Art Honor Society\n"
				+"null\n"
				+"Jennifer_Sherman@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Melissa Kiehl\n"
				+"GT\n"
				+"null\n"
				+"Future Educators of America, Tourette’s Awareness Club\n"
				+"null\n"
				+"melissa_kiehl@hcpss.org\n"
				+"http://MtHebronGT.com\n"
				+"'\n"
				+"Thomas Fruscello\n"
				+"Science\n"
				+"2, 5\n"
				+"null\n"
				+"null\n"
				+"thomas_fruscello@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Andrew Bright\n"
				+"Mathematics\n"
				+"5, 6\n"
				+"Class of 2015\n"
				+"null\n"
				+"abright@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Leslie Ammann\n"
				+"World Languages\n"
				+"4A, 4B\n"
				+"National Honor Society\n"
				+"null\n"
				+"Leslie_Ammann@hcpss.org\n"
				+"www.mhhs.studentmoodle.com\n"
				+"'\n"
				+"Valerie Fawcett\n"
				+"Mathematics\n"
				+"4A, 4B\n"
				+"Freshman Class Board\n"
				+"null\n"
				+"valerie_fawcett@gmail.com\n"
				+"null\n"
				+"'\n"
				+"Bryna Weiss\n"
				+"Social Studies\n"
				+"1, 4A\n"
				+"It’s Academic\n"
				+"null\n"
				+"bryan_weiss@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Justine Hughes\n"
				+"World Languages\n"
				+"4A, 4B\n"
				+"National French Honor Society\n"
				+"null\n"
				+"justine_hughes@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Paul Sabota\n"
				+"Science\n"
				+"4A, 4B\n"
				+"Anime Club\n"
				+"null\n"
				+"paul_sabota@hcpss.org\n"
				+"http://mrsabota.weebly.com\n"
				+"'\n"
				+"Amy Comberiate\n"
				+"English\n"
				+"4A, 4B\n"
				+"STARs Theater Critics, Literary Magazine, Writing Center\n"
				+"null\n"
				+"Amy_Comberiate@hcpss.org\n"
				+"http://sites.google.com/site/mrscomberiate/home\n"
				+"'\n"
				+"Valerie Wetstone\n"
				+"Science\n"
				+"5, 6\n"
				+"Science Club, Science National Honor Society\n"
				+"null\n"
				+"valerie_wetstone@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Daniel Pendley\n"
				+"Band\n"
				+"4A, 4B, 5\n"
				+"Marching Unit, Jazz Ensemble, Dixieland Jazz, Pit Orchestra\n"
				+"null\n"
				+"dan.pendley@gmail.com, dpendley@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Jessica Rosenberg\n"
				+"Science\n"
				+"4A, 5\n"
				+"null\n"
				+"null\n"
				+"jessica_tjok@hcpss.org\n"
				+"jrosenberg.weebly.com\n"
				+"'\n"
				+"Robert (Bobby) Macheel\n"
				+"Social Studies\n"
				+"null\n"
				+"null\n"
				+"JV Boys Lacrosse  \n"
				+"Robert_Macheel@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Shannon Davis\n"
				+"English\n"
				+"3, 5\n"
				+"null\n"
				+"null\n"
				+"shannon_davis@hcpss.org\n"
				+"http:www.planbookedu.com/s/4I25U\n"
				+"'\n"
				+"Michael Moynihan\n"
				+"Special Education\n"
				+"1, 4A\n"
				+"FCA\n"
				+"Varsity Volleyball, Allied Bowling\n"
				+"Michael_Moynihan@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Jennifer Green\n"
				+"Mathematics\n"
				+"1, 3\n"
				+"South Asian Club\n"
				+"null\n"
				+"jennifer_green@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Greg Murach\n"
				+"Mathematics\n"
				+"1, 2\n"
				+"Class of 2013\n"
				+"null\n"
				+"gregory_murach@gmail.com\n"
				+"null\n"
				+"'\n"
				+"Leigh Langmead\n"
				+"Mathematics\n"
				+"1, 3\n"
				+"null\n"
				+"JV Field Hockey\n"
				+"Leigh_Langmead@hcpss.org\n"
				+"http://web.hcpss.org/~langmead\n"
				+"'\n"
				+"Lisa Vitali\n"
				+"English\n"
				+"1, 4A\n"
				+"Class of 2013\n"
				+"null\n"
				+"lisa_vitali@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Stephan L. Hise\n"
				+"CTE\n"
				+"4A, 4B\n"
				+"Alpha Achievers\n"
				+"null\n"
				+"stephan_hise@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Angela Sugg\n"
				+"Social Studies\n"
				+"4A, 4B\n"
				+"Student Government Association, Berzerkers Spirit Club\n"
				+"null\n"
				+"angela_sugg@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Daniel Harman\n"
				+"Health\n"
				+"2, 3\n"
				+"null\n"
				+"JV Wrestling\n"
				+"daniel_harman@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Valerie McNeely\n"
				+"Physical Education\n"
				+"1, 4B\n"
				+"null\n"
				+"Lancers, Volleyball, JV Field Hockey, Track\n"
				+"valerie_mcneely@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Jennifer Goodwin\n"
				+"English\n"
				+"4B, 5\n"
				+"Class of 2014\n"
				+"null\n"
				+"jennifer_goodwin@comcast.net\n"
				+"null\n"
				+"'\n"
				+"Cyndie Fagan\n"
				+"English\n"
				+"1, 5, 6\n"
				+"Class of 2013, Graduation Coordinator\n"
				+"null\n"
				+"cynthia_fagan@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Cristine Arag�n\n"
				+"Social Studies\n"
				+"5, 6\n"
				+"null\n"
				+"null\n"
				+"christine_aragon@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Julianne Cochran\n"
				+"Mathematics\n"
				+"4A, 4B\n"
				+"Class of 2015\n"
				+"null\n"
				+"julianna_cochran@hcpss.org\n"
				+"sites.google.com/site/juliannenicole\n"
				+"'\n"
				+"Claudia Tonguino\n"
				+"World Languages\n"
				+"1, 2\n"
				+"Spanish Club\n"
				+"null\n"
				+"claudia_tonguino@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Larry Luthe\n"
				+"Mathematics\n"
				+"3, 6\n"
				+"null\n"
				+"Soccer\n"
				+"lawrence_luthe@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Erin Abrams\n"
				+"Special Education\n"
				+"4A, 4B\n"
				+"null\n"
				+"null\n"
				+"erin_abrams@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Kelly Caprarola\n"
				+"Mathematics\n"
				+"4A, 6\n"
				+"null\n"
				+"JV Basketball, Allied Soccer\n"
				+"kelly_caprarola@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Suzanne Stafford\n"
				+"Science\n"
				+"1, 3\n"
				+"Architecture Club\n"
				+"null\n"
				+"suzanne_stafford@hcpss.org\n"
				+"stafforescience.weebly.com\n"
				+"'\n"
				+"Christina Rosendorf\n"
				+"Science\n"
				+"1, 3\n"
				+"null\n"
				+"null\n"
				+"crosendorf@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Brittany Gutierrez\n"
				+"Mathematics\n"
				+"5, 6\n"
				+"null\n"
				+"Varsity Cheerleading\n"
				+"brittany_gutierrez@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Trish Ewart\n"
				+"Special Education\n"
				+"4A, 4B, 5, 6\n"
				+"Best Buddies\n"
				+"null\n"
				+"patricia_ewart@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Jaqueline Lopata\n"
				+"World Languages\n"
				+"4A,\n"
				+"Latin Club, Latin National Honor Society\n"
				+"null\n"
				+"jaqueline_lopata@hcpss.org\n"
				+"lopatalatin.weebly.com\n"
				+"'\n"
				+"Tom Sankey\n"
				+"Mathematics\n"
				+"4B, 5, 6\n"
				+"Director of fall show, Director of spring musical\n"
				+"null\n"
				+"thomas_sankey@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Gail Love\n"
				+"World Languages\n"
				+"3, 4B\n"
				+"German Club\n"
				+"null\n"
				+"gail_love@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Heather Leatherman\n"
				+"Art\n"
				+"1, 2, 3, 4A, 4B\n"
				+"null\n"
				+"null\n"
				+"hleatherman@hcpss.org\n"
				+"leathermanartone.edublogs.org\n"
				+"'\n"
				+"Jared Ettinger\n"
				+"Social Studies\n"
				+"5, 6\n"
				+"null\n"
				+"null\n"
				+"jared_ettinger@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Jill Singleton\n"
				+"ESOL\n"
				+"1, 5\n"
				+"null\n"
				+"null\n"
				+"jsingleton@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Todd Decrispino\n"
				+"Physical Education\n"
				+"4A, 6\n"
				+"null\n"
				+"Boys Cross Country, Varsity Wrestling, JV Baseball\n"
				+"todd-decrispino@hcpss.org\n"
				+"hebronwrestling.com\n"
				+"'\n"
				+"Janna Freishtat\n"
				+"Special Education\n"
				+"1, 5\n"
				+"null\n"
				+"null\n"
				+"janna_freishtat@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Sandy Davis\n"
				+"English\n"
				+"3, 5\n"
				+"null\n"
				+"null\n"
				+"sandra_davis@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Meagan Markowski\n"
				+"World Languages\n"
				+"5, 6\n"
				+"null\n"
				+"null\n"
				+"megan_markowski@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Ann Johnston\n"
				+"Special Education/Mathematics\n"
				+"3, 4B\n"
				+"Student of the Month Program\n"
				+"null\n"
				+"ann_johnston@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Sara Tagget\n"
				+"Mathematics\n"
				+"4A, 4B\n"
				+"null\n"
				+"Math Team\n"
				+"sara_tagget@hcpss.org\n"
				+"sites.google.com/site/stagget\n"
				+"'\n"
				+"Rachel Fulchino\n"
				+"English\n"
				+"4A, 6\n"
				+"null\n"
				+"null\n"
				+"Rachel_Fulchino@hcpss.org\n"
				+"null\n"
				+"'\n"
				+"Hannah Gonzalez\n"
				+"World Languages\n"
				+"2, 3\n"
				+"Los Vikingos, Spanish National Honor Society\n"
				+"null\n"
				+"hannah_gonzalez@hcpss.org\n"
				+"mhhs.studentmoodle.com\n"
				+"'\n"
				+"Jennifer Olchowski\n"
				+"Social Studies\n"
				+"1, 6\n"
				+"null\n"
				+"null\n"
				+"Jennifer_Olchowski@hcpss.org\n"
				+"null\n";
		iScanner = new Scanner(thingString);
		StringBuilder teachersBuilder=new StringBuilder();
		while(iScanner.hasNext()) {
			teachersBuilder.append(iScanner.nextLine());
			teachersBuilder.append("\n");
		}
		String fullList=teachersBuilder.toString();
		String[] seperatedList=fullList.split("'");
		String[] blah=seperatedList[0].split("\n");
		String temp=blah[0].substring(0, 6);	
		String name=temp;
		String department=blah[1];
		String planning=blah[2];
		String club=blah[3];
		String sport=null;
		String email=blah[5];
		String website=null;
		teachers[0]=new Teacher(name, department, planning, club, sport, email, website);
		for (int i = 1; i < seperatedList.length; i++) {
			blah=seperatedList[i].split("\n");
			name=blah[1];
			department=blah[2];
			if (blah[3].equals("null")) {
				planning=null;
			}else planning=blah[3];
			if (blah[4].equals("null")) {
				sport=null;
			}else sport=blah[4];
			if (blah[5].equals("null")) {
				club=null;
			}else club=blah[5];
			if (blah[6].equals("null")) {
				email=null;
			}else email=blah[6];
			if (blah[7].equals("null")) {
				website=null;
			}else website=blah[7];
			teachers[i]=new Teacher(name, department, planning, sport, club, email, website);
		}
		return teachers;
	}
}